Create Checkbox
js-tasks-ru/htmlcss-20240614_androsphilippos pull request #17
Opened 2024-07-17 05:22 UTC by Filippoussis

2024-07-17 05:23 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-17 05:51 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-19 15:43 UTC, GSemikozov requested changes

2024-07-19 15:43 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  display: flex;
лучше все-таки inline-flex

2024-07-19 17:30 UTC, Filippoussis commented on 07-lection5/01-checkbox/checkbox.css
> +  display: flex;
заменил

2024-07-20 20:35 UTC, GSemikozov approved these changes

2024-07-20 20:35 UTC, merged