Create Input
js-tasks-ru/htmlcss-20240614_androsphilippos pull request #20
Opened 2024-07-20 03:41 UTC by Filippoussis

2024-07-20 03:42 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-20 20:33 UTC, GSemikozov requested changes

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +    <label class="input" for="input-1">
а вот инпут заворачивать в лейбл в данном случае не надо)

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <span class="input__label">Default</span>
вот это и есть label

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +          class="input__field input__field--success"
модификатор должен быть общим для всех элементов, а значит - это будет модификатор блока

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  gap: 4px;
5

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__icon {
по умолчанию - скрыта

2024-07-20 20:33 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__field--success {
а показываем нужную в зависимости от модификатора блока

2024-07-21 03:50 UTC, Filippoussis commented on 07-lection5/04-input/input.css
> +.input__icon {
поправил

2024-07-21 03:50 UTC, Filippoussis commented on 07-lection5/04-input/input.css
> +.input__field--success {
поправил

2024-07-21 03:50 UTC, Filippoussis commented on 07-lection5/04-input/index.html
> +          class="input__field input__field--success"
поправил

2024-07-21 03:50 UTC, Filippoussis commented on 07-lection5/04-input/index.html
> +      <span class="input__label">Default</span>
поправил

2024-07-21 03:50 UTC, Filippoussis commented on 07-lection5/04-input/index.html
> +    <label class="input" for="input-1">
поправил

2024-07-21 03:51 UTC, Filippoussis commented on 07-lection5/04-input/input.css
> +  gap: 4px;
заменил на 5

2024-07-21 12:13 UTC, GSemikozov approved these changes

2024-07-21 12:13 UTC, merged