Create Inner Avatar Page
js-tasks-ru/htmlcss-20240614_androsphilippos pull request #24
Opened 2024-07-27 00:45 UTC by Filippoussis

2024-07-27 00:46 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-27 14:44 UTC, GSemikozov requested changes

2024-07-27 14:44 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title--inner {
.footer--inner .title {}

2024-07-27 14:44 UTC, GSemikozov commented on components/header/header.css
> +.header__content--inner {
.header--inner .header__content {}

2024-07-27 15:14 UTC, Filippoussis commented on components/header/header.css
> +.header__content--inner {
поправил

2024-07-27 15:14 UTC, Filippoussis commented on components/footer/footer.css
> +.footer__title--inner {
поправил

2024-07-27 15:15 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-07-27 15:45 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-07-28 11:52 UTC, GSemikozov approved these changes

2024-07-28 11:52 UTC, merged