Create histogram
js-tasks-ru/htmlcss-20240614_androsphilippos pull request #6
Opened 2024-06-23 21:11 UTC by Filippoussis

2024-06-23 21:11 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-24 13:25 UTC, GSemikozov requested changes

2024-06-24 13:25 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
лишнее

2024-06-24 13:25 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  position: absolute;
я бы рекомендовал оставить в общем потоке, просто выравнивать флексом

2024-06-24 13:25 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
лишнее

2024-06-24 13:25 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 9px;
flex-basis

2024-06-25 19:08 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-25 19:34 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-06-25 19:35 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
убрал

2024-06-25 19:35 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  position: absolute;
оставил в общем потоке

2024-06-25 19:35 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
убрал justify-content

2024-06-25 19:35 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  width: 9px;
заменил на flex-basis

2024-06-29 05:02 UTC, GSemikozov requested changes

2024-06-29 05:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +
и еще хитрый отступ сверху margin/padding-top 3px )

2024-06-29 05:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 40px;
39 )

2024-06-29 05:02 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  flex-direction: column-reverse;
можно на уровне родителя align-items: flex-end

2024-06-29 05:02 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +        <div class="histogram__item" data-value="50">
если бы здесь закидывали в процентах

2024-06-29 05:02 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +          <div
то это был бы лишний элемент и верста была бы проще

2024-06-30 05:53 UTC, Filippoussis commented on 04-lection2/01-histogram/index.html
> +          <div
убрал

2024-06-30 05:53 UTC, Filippoussis commented on 04-lection2/01-histogram/index.html
> +        <div class="histogram__item" data-value="50">
высоту применил к histogram__item

2024-06-30 05:53 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  flex-direction: column-reverse;
применил

2024-06-30 05:54 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +  margin-top: 40px;
исправил

2024-06-30 05:54 UTC, Filippoussis commented on 04-lection2/01-histogram/histogram.css
> +
добавил

2024-07-02 19:32 UTC, GSemikozov approved these changes

2024-07-02 19:32 UTC, merged