Create Tooltip
js-tasks-ru/htmlcss-20240614_androsphilippos pull request #9
Opened 2024-06-26 19:13 UTC by Filippoussis

2024-06-26 19:14 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-06-29 05:06 UTC, GSemikozov requested changes

2024-06-29 05:06 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +  top: calc(-100% - 24px - 4px);
как-то сложно с минусами) может bottom: calc(100% + /*высота стрелки, а не высота иконки*/)

2024-06-30 04:50 UTC, Filippoussis commented on 05-lection3/01-tooltip/tooltip.css
> +  top: calc(-100% - 24px - 4px);
 заменил на bottom

2024-07-02 19:33 UTC, GSemikozov approved these changes

2024-07-02 19:33 UTC, merged